---
#
#      Copyright (c) 2016 F5 Networks
#      All rights reserved.
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will reset to a factory default
#      configuration. It will leave the license and hostname in tact.
#      Edit the attributes accordingly.
#      Requires Ansible 2.4 or higher

- name: Reset the BIG-IP configuration, for example, to RMA the device
  hosts: bigip[2]
  connection: local

  tasks:
   - name: resetting now
     bigip_config:
         reset: "yes"
         save: "no"
         server: "bigip"
         password: "admin"
         user: "Kenkar@00"
         validate_certs: "no"
     delegate_to: localhost
